services:
  - type: web
    name: delivery-route-app
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker -w 2 -b 0.0.0.0:$PORT web_main:app
    autoDeploy: true
    envVars:
      - key: BASE_DIR
        value: /data
    disk:
      name: data
      mountPath: /data
      sizeGB: 2
